# Generated by Django 5.2.4 on 2026-07-28 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=9)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Connect_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('twitter', 'X / Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('website', 'Other website')], max_length=20)),
                ('url_or_handle', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Kehinde Omoyayi CV', max_length=120)),
                ('file', models.FileField(upload_to='project/cv/')),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CV / Resume',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Open_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title_and_company', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recommendations/')),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(help_text='e.g. 18%, ₦7M, ₦500K+', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='tools_pics')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='certificate_cat', to='main.category')),
            ],
            options={
                'ordering': ['order', '-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project/dashboard/thumbnails/')),
                ('embed_type', models.CharField(choices=[('powerbi', 'Power BI'), ('tableau', 'Tableau Public'), ('iframe', 'Other embeddable URL (generic iframe)'), ('image', 'Static image only (no live embed)')], default='powerbi', max_length=10)),
                ('embed_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='dashboards', to='main.category')),
                ('technologies', models.ManyToManyField(blank=True, related_name='dashboards', to='main.tools')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(help_text='e.g. 65.7%  or  12.4M', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='main.dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('summary', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(default='projects/covers/book.png', upload_to='projects/covers/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='projects/pdfs/')),
                ('allow_pdf_download', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='main.category')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='main.tools')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('dataset', 'Dataset'), ('report', 'Report')], default='dataset', max_length=10)),
                ('file', models.FileField(upload_to='project/dataset/')),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_reports', to='main.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('github', 'GitHub repository'), ('live_demo', 'Live demo / app'), ('article', 'Article / write-up'), ('video', 'Video walkthrough'), ('other', 'Other link')], default='github', max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('abstract', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='research/cover/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='research/pdfs/')),
                ('external_url', models.URLField(blank=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(blank=True, related_name='publications', to='main.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Kehinde Omoyayi', max_length=120)),
                ('headline', models.CharField(default='Turning Data Into Insights. Building Solutions. Creating Impact.', max_length=200)),
                ('short_bio', models.TextField(default='I transform raw data into actionable insights, build scalable backend systems, and develop intelligent solutions to solve real world problems.')),
                ('note', models.TextField(default='Most Analysts shows you what happened. I show you what to do next.')),
                ('location', models.CharField(default='Nigeria', max_length=100)),
                ('education', models.CharField(default='MSc. Data Science', max_length=100)),
                ('experience_years', models.CharField(default='4+ Years Exp.', max_length=100)),
                ('about_me', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('story', models.TextField(blank=True)),
                ('availability_status', models.CharField(default='Available for Discussion', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.cvdocument')),
                ('open_to_roles', models.ManyToManyField(blank=True, to='main.open_roles')),
                ('role_titles', models.ManyToManyField(blank=True, to='main.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Currently_Focused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('icon_svg', models.FileField(blank=True, null=True, upload_to='focus_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='main.siteprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
