# Generated by Django 5.2.17 on 2026-08-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dashboard_related_datasets_dashboard_related_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect_link',
            name='url_or_handle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
